apiVersion: v2
name: corda
description: A Helm chart for Corda
type: application
version: 5.0.0-Hawk1.0.1
appVersion: unstable
dependencies:
- name: corda-lib
  version: 0.1.0
  repository: file://../corda-lib
