kind: ServiceAccount
apiVersion: v1
metadata:
  name: corda-privileged
  namespace: e2e-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: corda-privileged
  namespace: e2e-test
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: corda-privileged
  namespace: e2e-test
subjects:
  - kind: ServiceAccount
    name: corda-privileged
    namespace: e2e-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: corda-privileged
