{{- $_ := set . "worker" "flow" }}
{{- define "flowworker.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corda.workerName" . }}-{{ .flowworkerDeployment }}
  labels:
    {{- include "corda.workerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workers.flow.replicaCount }}
  selector:
    matchLabels:
      {{- include "corda.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "corda.workerAnnotations" . | nindent 8 }}
      labels:
        {{- include "corda.workerSelectorLabels" . | nindent 8 }}
    spec:
      {{- include "corda.podSecurityContext" . | nindent 6 }}
      {{- include "corda.imagePullSecrets" . | nindent 6 }}
      {{- include "corda.serviceAccount" . | nindent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                  - flow-worker
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ include "corda.workerName" . }}-{{ .flowworkerDeployment }}
        image: {{ include "corda.workerImage" . }}
        imagePullPolicy:  {{ .Values.imagePullPolicy }}
        {{- include "corda.containerSecurityContext" . | nindent 8 }}
        {{- include "corda.workerResources" . | nindent 8 }}
        env:
        {{- include "corda.workerEnv" . | nindent 10 }}
        {{- include "corda.configSaltAndPassphraseEnv" . | nindent 10 }}
        args:
        {{- include "corda.workerKafkaArgs" . | nindent 10 }}
          - -spassphrase=$(PASSPHRASE)
          - -ssalt=$(SALT)
        volumeMounts:
        {{- include "corda.workerVolumeMounts" . | nindent 10 }}
        ports:
        {{- if .Values.workers.flow.debug.enabled }}
          - name: debug
            containerPort: 5005
        {{- end }}
          - name: monitor
            containerPort: 7000
        {{- if .Values.workers.flow.profiling.enabled }}
          - name: profiling
            containerPort: 10045
        {{- end }}
        {{- include "corda.workerProbes" . | nindent 8 }}
      initContainers:
      {{ include "corda.kafkaSaslInitContainer" . | nindent 8 }}
      volumes:
      {{- include "corda.workerVolumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
{{ if .Values.deployments.v5_0.enabled }}
{{- $_ := set . "flowworkerDeployment" "5-0" }}
{{- template "flowworker.deployment" . }}
{{ end }}
{{ if .Values.deployments.v5_1.enabled }}
{{- $_ := set . "flowworkerDeployment" "5-1" }}
---
{{- template "flowworker.deployment" . }}
{{ end }}
